schema_version: "1.0"
id: "pets-in-turkey"
name: "Pets in Turkey"
enabled: true
scraper:
  class_name: "PetsInTurkeyScraper"
  module: "scrapers.pets_in_turkey.petsinturkey_scraper"
  config:
    rate_limit_delay: 3.0 # Increased for API calls
    max_retries: 3
    timeout: 60
    skip_existing_animals: true
    enable_llm_profiling: true
metadata:
  website_url: "https://www.petsinturkey.org/"
  description: "We are a group of animal and nature loving people living in Switzerland with close ties to Turkey. Our mission is to help all breeds of cats and dogs in Turkey that are regularly being abandoned in large numbers."
  location:
    country: "TR" # Organization's base country
    city: "Izmir" # Organization's base city
  service_regions: ["TR"]
  ships_to: [
      "UK",
      "CH",
      "NO",
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "GR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ] # Countries they ship to
  social_media:
    website: "https://www.petsinturkey.org/"
    facebook: "https://www.facebook.com/petsinturkey/"
    instagram: "https://www.instagram.com/petsinturkey/"
  established_year: 2018
  logo_url: "https://images.rescuedogs.me/rescue_dogs/organizations/org-logo-pets-in-turkey.jpg"
  adoption_fees:
    usual_fee: 550
    currency: "USD"
