export const BREED_CONSTANTS = {
  ITEMS_PER_PAGE: 12,
  MAX_POPULAR_BREEDS_DISPLAY: 12,
  MAX_BREED_GROUPS_DISPLAY: 8,
  MIN_DOGS_FOR_POPULAR_MIX: 15,
  MAX_POPULAR_MIXES: 6,
  MAX_GALLERY_IMAGES: 4,
  IMAGE_LOAD_THRESHOLD: "100px",
  MIN_TOUCH_TARGET_SIZE: 44,
  IMAGE_FADE_DURATION: 300,
  SWIPE_MIN_DISTANCE: 50,
  MAX_API_LIMIT: 1000,
  DEFAULT_REVALIDATE_TIME: 3600,
  MOBILE_CARD_WIDTH: "85%",
  TABLET_CARD_WIDTH: "45%",
} as const;

export const BREED_GROUP_NAMES = {
  HOUND: "Hound",
  SPORTING: "Sporting",
  HERDING: "Herding",
  WORKING: "Working",
  TERRIER: "Terrier",
  NON_SPORTING: "Non-Sporting",
  TOY: "Toy",
  MIXED: "Mixed",
} as const;

export const BREED_TYPES = {
  PUREBRED: "purebred",
  MIXED: "mixed",
  CROSSBREED: "crossbreed",
  UNKNOWN: "unknown",
} as const;
