-- Migration: Add LLM enrichment fields to animals table
-- Purpose: Store enriched data generated by LLM service

-- Add enriched description field
ALTER TABLE animals 
ADD COLUMN IF NOT EXISTS enriched_description TEXT;

-- Add dog profiler data as JSONB
ALTER TABLE animals
ADD COLUMN IF NOT EXISTS dog_profiler_data JSONB;

-- Add translations as JSONB (key-value pairs of language codes to translations)
ALTER TABLE animals
ADD COLUMN IF NOT EXISTS translations JSONB;

-- Add tracking fields for LLM processing
ALTER TABLE animals
ADD COLUMN IF NOT EXISTS llm_processed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS llm_model_used VARCHAR(100),
ADD COLUMN IF NOT EXISTS llm_processing_flags JSONB DEFAULT '{}';

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_animals_llm_processed_at ON animals(llm_processed_at);
CREATE INDEX IF NOT EXISTS idx_animals_dog_profiler_data ON animals USING GIN (dog_profiler_data);
CREATE INDEX IF NOT EXISTS idx_animals_translations ON animals USING GIN (translations);

-- Add LLM processing logs table for tracking and debugging
CREATE TABLE IF NOT EXISTS llm_processing_logs (
    id SERIAL PRIMARY KEY,
    animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE,
    processing_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    model_used VARCHAR(100),
    tokens_used INTEGER,
    processing_time_ms INTEGER,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for querying processing history
CREATE INDEX IF NOT EXISTS idx_llm_logs_animal_id ON llm_processing_logs(animal_id);
CREATE INDEX IF NOT EXISTS idx_llm_logs_created_at ON llm_processing_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_llm_logs_status ON llm_processing_logs(status);