name: Setup PostgreSQL Database
description: |
  Reusable action for setting up PostgreSQL test database from schema.sql.
  Note: uv must be pre-installed before using this action.

inputs:
  db-name:
    description: Database name
    required: false
    default: test_rescue_dogs
  db-user:
    description: Database user
    required: false
    default: postgres
  db-password:
    description: Database password
    required: false
    default: postgres
  db-host:
    description: Database host
    required: false
    default: localhost
  db-port:
    description: Database port
    required: false
    default: "5432"

runs:
  using: composite
  steps:
    - name: Wait for PostgreSQL
      shell: bash
      run: |
        for i in {1..15}; do
          if pg_isready -h ${{ inputs.db-host }} -p ${{ inputs.db-port }}; then
            echo "PostgreSQL is ready"
            exit 0
          fi
          echo "Waiting for PostgreSQL... attempt $i/15"
          sleep 2
        done
        echo "ERROR: PostgreSQL did not become ready after 15 attempts"
        exit 1

    - name: Create database
      shell: bash
      env:
        PGPASSWORD: ${{ inputs.db-password }}
      run: |
        if psql -h ${{ inputs.db-host }} -p ${{ inputs.db-port }} -U ${{ inputs.db-user }} \
          -c "CREATE DATABASE ${{ inputs.db-name }};" 2>&1; then
          echo "Database created successfully"
        else
          # Check if database already exists
          if psql -h ${{ inputs.db-host }} -p ${{ inputs.db-port }} -U ${{ inputs.db-user }} \
            -lqt | cut -d \| -f 1 | grep -qw ${{ inputs.db-name }}; then
            echo "Database already exists, continuing"
          else
            echo "ERROR: Failed to create database and database does not exist"
            exit 1
          fi
        fi

    - name: Grant privileges
      shell: bash
      env:
        PGPASSWORD: ${{ inputs.db-password }}
      run: |
        # Grant database privileges (always succeeds for owner)
        psql -h ${{ inputs.db-host }} -p ${{ inputs.db-port }} -U ${{ inputs.db-user }} \
          -d ${{ inputs.db-name }} \
          -c "GRANT ALL PRIVILEGES ON DATABASE ${{ inputs.db-name }} TO ${{ inputs.db-user }};"

        # Grant table privileges (may have no tables yet, which is expected)
        psql -h ${{ inputs.db-host }} -p ${{ inputs.db-port }} -U ${{ inputs.db-user }} \
          -d ${{ inputs.db-name }} \
          -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${{ inputs.db-user }};" 2>&1 || true

        # Grant sequence privileges (may have no sequences yet, which is expected)
        psql -h ${{ inputs.db-host }} -p ${{ inputs.db-port }} -U ${{ inputs.db-user }} \
          -d ${{ inputs.db-name }} \
          -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${{ inputs.db-user }};" 2>&1 || true

    - name: Initialize database schema
      shell: bash
      env:
        TESTING: "true"
        DB_HOST: ${{ inputs.db-host }}
        DB_PORT: ${{ inputs.db-port }}
        DB_NAME: ${{ inputs.db-name }}
        DB_USER: ${{ inputs.db-user }}
        DB_PASSWORD: ${{ inputs.db-password }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        uv run python -c "
        import sys
        from database.db_setup import initialize_database
        conn = initialize_database()
        if not conn:
            print('ERROR: Database schema initialization failed')
            sys.exit(1)
        print('Database schema initialized successfully')
        conn.close()
        "

