/**
 * Breed descriptions utility
 * Provides concise breed descriptions (100-150 words) for breed detail pages
 */

const BREED_DESCRIPTIONS = {
  'Galgo': `Spanish Greyhounds are gentle, affectionate sighthounds known for their calm nature and surprising laziness despite their athletic build. These "45 mph couch potatoes" prefer short exercise bursts followed by long naps on soft surfaces. Most rescue Galgos are retired hunting dogs who adapt beautifully to apartment living and quiet home environments. They're typically excellent with other dogs but retain strong prey drive toward small animals like cats and rabbits. Their thin skin and lean build require soft bedding, warm coats in cold weather, and protection from rough surfaces. These sensitive souls bond deeply with their families but can be initially reserved with strangers. They're naturally quiet, clean housemates who rarely bark and make minimal demands on their owners. Their gentle, intuitive nature makes them exceptional therapy dogs. Ideal for patient adopters seeking a low-maintenance, affectionate companion who appreciates calm energy and understands their independent yet loving personality.`,
  
  'Podenco': `Podencos are ancient Spanish hunting dogs with keen intelligence, athletic builds, and distinctive upright ears that give them an alert, fox-like expression. These energetic, independent spirits were bred to hunt rabbits across Mediterranean terrain, making them excellent jumpers and climbers who need tall, secure fencing. They're deeply loyal to their families but can be initially reserved with strangers, requiring patient socialization. Their high prey drive and escape-artist tendencies make them best suited for experienced owners who understand sighthound behavior. Despite their hunting heritage, they can be wonderfully affectionate indoor companions when given adequate physical and mental stimulation. These versatile dogs come in various sizes from small to large, all sharing the breed's unique charm and intelligence. Their short coat is remarkably low-maintenance, requiring only occasional brushing. With consistent positive training and proper outlets for their energy, they become devoted, entertaining companions who bring joy and mischief to their families.`,
  
  'Greyhound': `Greyhounds are gentle giants known as "45 mph couch potatoes." Despite their racing background, they're calm indoor companions who need surprisingly little exercise. These sweet-natured dogs are typically quiet, clean, and well-mannered. They bond strongly with their families and often do well in apartments. Most retired racers adapt quickly to home life, though they may need help learning about stairs and glass doors. Their thin skin and lean build mean they need soft bedding and warm coats in cold weather. They have a unique double-suspension gallop that allows them to reach incredible speeds. Despite their athletic ability, a daily walk and occasional sprint in a secure area satisfies their exercise needs. These dignified dogs rarely bark and are surprisingly good with children when properly introduced. Their calm demeanor makes them excellent companions for both active and sedentary lifestyles.`,
  
  'Collie': `Collies are intelligent, loyal herding dogs famous for their devotion to family. These sensitive souls are excellent with children and make wonderful family pets. They're highly trainable and eager to please, though they can be vocal. Collies need regular exercise and mental stimulation to prevent boredom. Their beautiful coat requires regular grooming. They thrive in homes where they can be part of daily activities. Their gentle nature and intuitive understanding of human emotions make them excellent therapy and companion dogs. Originally bred in Scotland for herding sheep, they retain their protective instincts without aggression. Collies excel in obedience, agility, and herding trials. They form deep bonds with all family members and are known for their remarkable ability to sense when someone needs comfort. Their weather-resistant double coat sheds seasonally but protects them in various climates.`,
  
  'Cocker Spaniel': `Cocker Spaniels are cheerful, affectionate dogs with gentle temperaments. These medium-sized companions are known for their beautiful, silky coats and expressive eyes. They're excellent family dogs who love children and get along well with other pets. Cockers are intelligent and trainable but can be sensitive. They need regular exercise and enjoy activities like fetch and swimming. Their coat requires regular grooming to prevent matting. These adaptable dogs do well in various living situations as long as they receive plenty of attention and affection. Originally bred as hunting dogs, they retain a keen nose and love of exploration. Their merry personality and wagging tail earn them the nickname "merry cocker." They're prone to ear infections due to their long, pendulous ears, requiring regular cleaning. These devoted companions thrive on human interaction and don't do well when left alone for extended periods.`,
  
  'German Shepherd Dog': `German Shepherds are versatile, intelligent working dogs known for loyalty and protective instincts. These confident dogs excel at various tasks and are devoted family guardians. They need experienced owners who can provide consistent training and socialization. GSDs require substantial daily exercise and mental stimulation. They're excellent with children they're raised with but can be reserved with strangers. Their double coat sheds year-round and needs regular brushing. These dogs thrive when given a job to do and form incredibly strong bonds with their families. Originally bred in Germany for herding sheep, they've become one of the most versatile working breeds. They excel in police work, military service, search and rescue, and as service dogs. Their keen intelligence makes them quick learners, but they need firm, fair leadership. Regular health screenings are important as they're prone to hip dysplasia. These noble dogs combine courage with a gentle nature toward their loved ones.`,
  
  'Siberian Husky': `Siberian Huskies are energetic, friendly dogs bred for endurance in harsh climates by the Chukchi people of Siberia. These social, pack-oriented dogs are known for their striking appearance, piercing blue or brown eyes, and vocal nature. They need substantial daily exercise and do best with active families who can provide mental stimulation. Huskies are intelligent but independent, making training a patient endeavor that requires consistency. They're typically good with children and other dogs but have high prey drive toward small animals. Their thick double coat requires regular brushing and sheds heavily twice yearly. These accomplished escape artists need secure fencing and plenty of mental stimulation to prevent destructive behavior. Their incredible endurance made them famous during the 1925 serum run to Nome, Alaska. These working dogs thrive in cold weather but can adapt to warmer climates with proper care and air conditioning.`,
  
  'Staffordshire Bull Terrier': `Staffordshire Bull Terriers, or "Staffies," are muscular, affectionate dogs renowned for their extraordinary love of people and legendary devotion to family, especially children. Despite their powerful appearance, they're gentle souls with patient temperaments that earned them the historical nickname "nanny dogs" in Victorian England. These energetic, intelligent companions require regular exercise and mental stimulation to channel their enthusiasm positively. They're eager to please but strong-willed, responding best to consistent, positive training methods. When properly socialized from puppyhood, Staffies typically enjoy other dogs' company and make excellent playmates. Their short, smooth coat is remarkably low-maintenance, requiring only occasional brushing. These loyal dogs form incredibly deep bonds with their families and thrive on human companionship, making them ideal pets for active households. Their natural courage and determination, combined with their playful, clownish nature, create devoted protectors always ready for adventure or cuddles.`,
  
  'French Bulldog': `French Bulldogs are charming, affectionate companions perfect for apartment living. These adaptable dogs are known for their distinctive "bat ears," wrinkled faces, and playful personalities. They're excellent with children and make wonderful family pets due to their patient, gentle nature. Frenchies need minimal exercise but enjoy short walks and playtime, making them ideal for less active owners. Their flat faces mean they're sensitive to heat and need climate-controlled environments to prevent breathing difficulties. They can be stubborn but respond well to positive training and food motivation. These social butterflies love being center of attention and thrive on human interaction. Their minimal grooming needs and calm indoor demeanor make them ideal urban companions. These adaptable dogs are equally happy in small apartments or large homes, as long as they're with their beloved families.`,
  
  'Beagle': `Beagles are friendly, curious hounds with merry personalities and excellent noses developed for rabbit hunting in England. These pack dogs are social and typically great with children and other dogs, making them ideal family companions. They're sturdy, medium-sized dogs who need regular exercise to prevent weight gain, as they're prone to obesity. Beagles can be vocal and will "bay" when excited or following a scent trail, which potential owners should consider. Their strong hunting instincts mean they need secure fencing and leash walking, as they'll follow interesting scents anywhere. They're intelligent but can be stubborn, often following their noses over commands during training sessions. Their short, weather-resistant coat is easy to maintain with regular brushing. These cheerful, even-tempered dogs make wonderful family pets for active households who can provide mental stimulation. Their gentle nature and moderate size have made them one of America's most popular family dogs for generations.`,
  
  'Cavalier King Charles Spaniel': `Cavalier King Charles Spaniels are gentle, affectionate toy spaniels perfect for companionship. These adaptable dogs are equally happy on adventures or cuddling on laps, embodying the perfect balance of sporting dog and lap dog. They're excellent with children, seniors, and other pets, making them ideal for multi-generational households. Cavaliers are intelligent and eager to please, making training enjoyable. They need moderate exercise and love interactive play, but are content with daily walks and indoor games. Their silky coat comes in four color combinations and requires regular brushing to prevent tangles. These social dogs don't do well alone for long periods and thrive on human companionship. Their sweet, gentle nature and portable size make them ideal therapy dogs and family companions. They're prone to certain health issues, so choosing reputable rescue organizations is essential.`,
  
  'Labrador Retriever': `Labrador Retrievers are friendly, outgoing dogs known for their love of everyone they meet and unwavering loyalty. Originally bred in Newfoundland to help fishermen, these energetic companions excel as family pets, therapy dogs, and working partners. Labs are highly intelligent and eager to please, making them very trainable for both basic obedience and complex tasks. They need substantial daily exercise and love swimming, thanks to their water-resistant coat and webbed feet. These food-motivated dogs can gain weight easily, requiring careful portion control and regular activity. Labs are excellent with children and typically good with other pets, making them ideal family dogs. Their short, dense double coat sheds year-round and comes in yellow, black, or chocolate colors. These loyal, patient dogs thrive in active families who can match their enthusiasm for life. Their versatility has made them one of America's most popular breeds.`,
  
  'Jack Russell Terrier': `Jack Russell Terriers are small dogs with enormous personalities and endless energy. These intelligent, fearless terriers were bred for fox hunting and retain incredibly strong prey drive and determination. They need extensive daily exercise and mental stimulation to prevent destructive behavior, as boredom leads to creative mischief. JRTs are clever and independent thinkers, requiring patient, consistent training from owners who can match their wit. They can be territorial with other dogs and may not suit homes with small pets like cats or rabbits. Their minimal grooming needs are offset by their exceptionally high activity requirements. These spirited, athletic dogs are best for experienced, active owners who appreciate their bold, entertaining nature and can provide adequate physical and mental challenges. Despite their small size, they're fearless and will take on much larger opponents, requiring careful supervision and secure fencing.`,
  
  'Border Collie': `Border Collies are brilliant herding dogs considered the most intelligent breed, originally developed in the Scottish Borders for sheep herding. These intense, focused workers need jobs to stay happy and balanced, as their incredible intelligence requires constant mental challenges. They require extensive physical and mental exercise daily, often needing several hours of activity and stimulation. Border Collies excel at dog sports, obedience training, and agility but can develop obsessive behaviors without proper outlets. They're loyal and affectionate with family but may be reserved with strangers, sometimes showing herding instincts with children and other pets. Their weather-resistant double coat needs regular brushing and comes in various colors, most commonly black and white. These dogs aren't suited for casual pet owners; they thrive with active, dedicated handlers who understand their working nature and can channel their incredible drive into productive activities.`,
  
  'Bulldog': `Bulldogs are gentle, affectionate companions known for their distinctive wrinkled faces, pushed-in noses, and sturdy, muscular builds. Despite their tough appearance, they're sweet-natured and excellent with children, earning them the title of ideal family pets. Originally bred in England for bull-baiting, modern Bulldogs are peaceful, low-energy dogs perfect for apartment living, needing only moderate exercise due to their breathing limitations. Bulldogs are prone to overheating and need climate-controlled environments, especially during summer months. They can be stubborn but respond well to patient, consistent training with positive reinforcement. Their facial wrinkles need regular cleaning to prevent skin infections. These loyal, comical dogs form incredibly strong bonds with their families and are known for their entertaining personalities. Their calm demeanor and minimal exercise needs make them ideal companions for less active households.`,
  
  'Poodle': `Poodles are intelligent, athletic dogs that come in three sizes (Standard, Miniature, and Toy) but share similar temperaments and remarkable intelligence. Originally bred in Germany as water retrievers, these highly trainable companions excel at various activities from agility and obedience to therapy work and competitive sports. They're typically good with children and other pets when properly socialized. Poodles need regular exercise and mental stimulation to prevent boredom, as their active minds require constant engagement. Their curly, hypoallergenic coat requires professional grooming every 6-8 weeks and daily brushing to prevent matting. They're sensitive, intuitive dogs who thrive on positive reinforcement and form deep bonds with their families. These elegant, playful dogs make excellent family pets for those willing to maintain their grooming needs and match their active nature. Their versatility and trainability have made them popular choices for service work.`,
  
  'Yorkshire Terrier': `Yorkshire Terriers are tiny dogs with big personalities and brave hearts, originally bred in 19th century England to catch rats in textile mills. These portable companions are deeply affectionate with family members but can be suspicious of strangers, making them excellent watchdogs despite their small size. Yorkies are intelligent and trainable but can be stubborn, requiring patient training. Despite their toy size, they need daily exercise and mental stimulation. Their long, silky coat requires daily brushing to prevent matting and regular professional grooming. They can be quite vocal and make excellent alert dogs, though this trait may need management in apartment settings. These terriers may not suit homes with very young children due to their delicate size and sometimes snappy nature when mishandled. Their adaptability, loyalty, and small size make them perfect for apartment living with devoted owners who understand their terrier temperament.`,
  
  'Shih Tzu': `Shih Tzus are affectionate lap dogs bred for companionship in Chinese imperial palaces, where they were treasured by royalty for centuries. These friendly, outgoing dogs love everyone they meet and make excellent family pets with their naturally happy disposition. They're remarkably adaptable to various living situations and need only moderate exercise, making them perfect for apartment life. Shih Tzus are intelligent but can be stubborn during training, responding best to positive reinforcement and patience. Their long, luxurious double coat comes in many color combinations and requires daily brushing and regular professional grooming. They're typically excellent with children and other pets when properly socialized. These brachycephalic dogs don't tolerate heat well due to their flat faces and may need climate control in warm weather. Their cheerful disposition, portable size, and loving nature make them ideal companions for apartments, seniors, and families seeking a devoted companion who thrives on human attention.`,
  
  'Lurcher': `Lurchers are unique sighthound crosses, traditionally combining Greyhounds or Whippets with terriers or collies, creating dogs that perfectly blend speed with intelligence. Originally developed by British poachers who needed fast, quiet hunting companions, these gentle souls have evolved into wonderful family pets. They're true "part-time athletes" who switch seamlessly between intense activity and complete couch potato mode. Most Lurchers are excellent with children and integrate well with other dogs when properly socialized. Like all sighthounds, their thin skin and lean build require soft bedding and warm coats during cold weather. They retain strong prey drive toward small animals, necessitating secure fencing and leash control. These adaptable dogs vary widely in size, coat type, and temperament depending on their parentage, but all share the sighthound's characteristic gentle, sensitive nature. Ideal for families who appreciate their unique blend of athleticism and affection.`,
  
  'Mixed Breed': `Mixed breed dogs combine traits from multiple breeds, creating unique personalities and appearances that make each dog truly one-of-a-kind. These special companions often have fewer inherited health issues due to genetic diversity, a phenomenon known as hybrid vigor. Every mixed breed is different, with temperaments ranging from calm to energetic, sizes from tiny to large, making them suitable for various lifestyles. They can excel at any activity from couch warming to agility, therapy work to hiking adventures. Mixed breeds often display the best qualities of their component breeds while mellowing extreme traits. Their unpredictable adult size and temperament make them delightful adventures, keeping families guessing about their dog's final appearance and personality. These special dogs prove that pedigree isn't necessary for unconditional love, loyalty, and the perfect family match. Rescue mixed breeds particularly shine as grateful, devoted companions who seem to understand they've been given a second chance.`,

  'Pointer': `Pointers are energetic, athletic sporting dogs originally bred in England for hunting game birds, with an instinctive ability to "point" at quarry by freezing in position. These noble, well-balanced dogs are known for their stamina, intelligence, and strong work ethic that translates beautifully into family life. They're typically gentle, even-tempered companions who bond deeply with their families while maintaining a dignified, somewhat independent nature. Pointers need substantial daily exercise and mental stimulation, thriving with active owners who enjoy running, hiking, or outdoor activities. Their strong hunting instincts mean they may chase small animals, requiring secure fencing and leash control in unfenced areas. These dogs are generally excellent with children and other dogs when properly socialized from puppyhood. Their short, easy-care coat comes in various color combinations and requires minimal grooming. Pointers make devoted family companions for households that can match their energy levels and appreciate their loyal, hardworking nature.`,

  'Bichon Frise': `Bichon Frises are cheerful, fluffy companions with hypoallergenic coats and irresistibly merry personalities that have charmed families for centuries. Originally developed in the Mediterranean region, these small white dogs were treasured by European nobility and sailors alike for their adaptable, loving nature. They're remarkably social dogs who thrive on human interaction and typically get along wonderfully with children, other dogs, and even cats when properly introduced. Bichons are intelligent and eager to please, making them relatively easy to train, though they can be sensitive and respond best to positive reinforcement methods. Their distinctive cotton-ball appearance requires professional grooming every 4-6 weeks and daily brushing to prevent matting, but their coats don't shed significantly. These adaptable dogs are content with moderate exercise and indoor play, making them excellent apartment companions. Their playful, affectionate nature and moderate size make them ideal family pets for those seeking a devoted, entertaining companion who brings joy and laughter to every day.`,

  'Chihuahua': `Chihuahuas are the world's smallest dog breed, but what they lack in size they make up for in personality, courage, and fierce devotion to their families. Originally from Mexico, these tiny companions typically weigh between 2-6 pounds but possess the confident attitude of much larger dogs. They're intensely loyal to their owners, often bonding most closely with one person while remaining somewhat aloof with strangers. Despite their fragile appearance, Chihuahuas are surprisingly sturdy and can live 14-16 years with proper care. They make excellent watchdogs, alerting families to visitors with their sharp, distinctive bark. These intelligent dogs are trainable but can be stubborn, requiring patient, consistent training methods. Their minimal exercise needs can be met with indoor play and short walks, making them perfect for apartment living. Chihuahuas come in both smooth and long coat varieties, with grooming needs varying accordingly. They're best suited for adults or families with older children who understand their delicate size and sometimes territorial nature.`,

  'Terrier': `Terriers are a diverse group of spirited, energetic dogs originally bred across Britain and Ireland for hunting vermin, from rats to foxes and badgers. While terrier breeds vary significantly in size and appearance, they share common traits of courage, determination, and strong prey drive that made them excellent working dogs. These confident, feisty companions are typically intelligent and loyal to their families while maintaining an independent streak that can make training challenging but rewarding. Most terriers need regular exercise and mental stimulation to prevent boredom-induced destructive behaviors, as their active minds require constant engagement. They're generally good with children when properly socialized but may be territorial with other dogs and unsuitable for homes with small pets like rabbits or hamsters. Their coats vary from smooth to wiry, with grooming needs depending on the specific type. These entertaining, bold dogs make devoted companions for experienced owners who appreciate their spirited nature and can provide firm, consistent leadership combined with plenty of physical activity and mental challenges.`,

  'Golden Retriever': `Golden Retrievers are friendly, intelligent sporting dogs originally developed in Scotland during the 1860s for retrieving waterfowl during hunting expeditions. These beautiful, medium-to-large dogs are renowned for their gentle mouths, lustrous golden coats, and exceptionally sweet temperaments that make them ideal family companions. They're highly trainable and eager to please, excelling as therapy dogs, service animals, and in various dog sports due to their intelligence and desire to work with humans. Golden Retrievers are typically excellent with children of all ages and get along well with other pets, making them perfect additions to multi-pet households. They need substantial daily exercise including swimming when possible, as they were bred for water work and naturally love aquatic activities. Their dense, water-repellent double coat requires regular brushing and sheds seasonally. These social dogs don't do well when left alone for extended periods and thrive on human interaction and family activities. Their patient, forgiving nature and moderate size make them one of America's most beloved family breeds.`,

  'Spaniel': `Spaniels are a diverse group of sporting dogs originally bred for flushing and retrieving game birds, known for their gentle mouths, keen noses, and eager-to-please attitudes. While spaniel breeds vary in size from the compact Cocker to the larger English Springer, they share common traits of affectionate, loyal temperaments and strong desires to work alongside their human partners. These intelligent, trainable dogs typically excel at various activities from hunting and agility to therapy work, adapting their energy levels to match their families' lifestyles. Most spaniels are naturally gentle with children and get along well with other pets when properly socialized, making them excellent family companions. They generally need moderate to high exercise depending on the specific breed, enjoying activities like fetch, swimming, and long walks. Their beautiful, often silky coats require regular grooming and can be prone to matting without proper care. These devoted, sensitive dogs form deep bonds with their families and thrive on positive interaction, making them ideal companions for those seeking an affectionate, versatile breed that combines sporting ability with wonderful family pet qualities.`
};

/**
 * Get breed description for a specific breed
 * @param {string} breedName - Name of the breed
 * @returns {string|null} - Breed description or null if not found
 */
export function getBreedDescription(breedName) {
  if (!breedName) return null;
  
  // Normalize breed name (trim and handle case)
  const normalizedBreed = breedName.trim();
  
  // Try exact match first
  if (BREED_DESCRIPTIONS[normalizedBreed]) {
    return BREED_DESCRIPTIONS[normalizedBreed];
  }
  
  // Try case-insensitive match
  const breedKey = Object.keys(BREED_DESCRIPTIONS).find(
    key => key.toLowerCase() === normalizedBreed.toLowerCase()
  );
  
  return breedKey ? BREED_DESCRIPTIONS[breedKey] : null;
}

/**
 * Get all available breed descriptions
 * @returns {Object} - Object with all breed descriptions
 */
export function getAllBreedDescriptions() {
  return { ...BREED_DESCRIPTIONS };
}

/**
 * Check if a breed has a description available
 * @param {string} breedName - Name of the breed
 * @returns {boolean} - True if description exists
 */
export function hasBreedDescription(breedName) {
  return getBreedDescription(breedName) !== null;
}

export default {
  getBreedDescription,
  getAllBreedDescriptions,
  hasBreedDescription
};