/**
 * Breed descriptions utility
 * Provides concise breed descriptions (100-150 words) for breed detail pages
 */

const BREED_DESCRIPTIONS = {
  'Galgo': `Spanish Greyhounds are gentle sighthounds known for their calm, affectionate nature. Despite their athletic build, they're surprisingly lazy, preferring short bursts of exercise followed by long naps. These sensitive souls thrive in quiet homes and bond deeply with their families. Most rescue Galgos are retired from hunting and adapt wonderfully to apartment living. They're typically good with other dogs but may chase small animals. Ideal for patient adopters who appreciate their independent yet loving personality. Their thin skin and lean build require soft bedding and warm clothing in cold weather. These graceful dogs are quiet, clean housemates who rarely bark. With proper introduction, they can coexist peacefully with cats. Their gentle demeanor makes them excellent therapy dogs, bringing comfort to those in need.`,
  
  'Podenco': `Podencos are energetic, independent hunters from Spain with keen intelligence and playful spirits. These athletic dogs need regular exercise and mental stimulation but can be wonderfully affectionate companions. They're known for their distinctive upright ears and alert expression. While they can be reserved with strangers, they're deeply loyal to their families. Podencos do best with experienced owners who understand their high prey drive and need for secure fencing. Their adaptable nature makes them suitable for various living situations with proper exercise. These versatile dogs come in different sizes, from small to large, each with unique charm. They're excellent jumpers and climbers, so tall, secure fencing is essential. With patience and positive training, they become devoted, entertaining companions. Their short coat is low-maintenance, requiring only occasional brushing to stay healthy and clean.`,
  
  'Greyhound': `Greyhounds are gentle giants known as "45 mph couch potatoes." Despite their racing background, they're calm indoor companions who need surprisingly little exercise. These sweet-natured dogs are typically quiet, clean, and well-mannered. They bond strongly with their families and often do well in apartments. Most retired racers adapt quickly to home life, though they may need help learning about stairs and glass doors. Their thin skin and lean build mean they need soft bedding and warm coats in cold weather. They have a unique double-suspension gallop that allows them to reach incredible speeds. Despite their athletic ability, a daily walk and occasional sprint in a secure area satisfies their exercise needs. These dignified dogs rarely bark and are surprisingly good with children when properly introduced. Their calm demeanor makes them excellent companions for both active and sedentary lifestyles.`,
  
  'Collie': `Collies are intelligent, loyal herding dogs famous for their devotion to family. These sensitive souls are excellent with children and make wonderful family pets. They're highly trainable and eager to please, though they can be vocal. Collies need regular exercise and mental stimulation to prevent boredom. Their beautiful coat requires regular grooming. They thrive in homes where they can be part of daily activities. Their gentle nature and intuitive understanding of human emotions make them excellent therapy and companion dogs. Originally bred in Scotland for herding sheep, they retain their protective instincts without aggression. Collies excel in obedience, agility, and herding trials. They form deep bonds with all family members and are known for their remarkable ability to sense when someone needs comfort. Their weather-resistant double coat sheds seasonally but protects them in various climates.`,
  
  'Cocker Spaniel': `Cocker Spaniels are cheerful, affectionate dogs with gentle temperaments. These medium-sized companions are known for their beautiful, silky coats and expressive eyes. They're excellent family dogs who love children and get along well with other pets. Cockers are intelligent and trainable but can be sensitive. They need regular exercise and enjoy activities like fetch and swimming. Their coat requires regular grooming to prevent matting. These adaptable dogs do well in various living situations as long as they receive plenty of attention and affection. Originally bred as hunting dogs, they retain a keen nose and love of exploration. Their merry personality and wagging tail earn them the nickname "merry cocker." They're prone to ear infections due to their long, pendulous ears, requiring regular cleaning. These devoted companions thrive on human interaction and don't do well when left alone for extended periods.`,
  
  'German Shepherd Dog': `German Shepherds are versatile, intelligent working dogs known for loyalty and protective instincts. These confident dogs excel at various tasks and are devoted family guardians. They need experienced owners who can provide consistent training and socialization. GSDs require substantial daily exercise and mental stimulation. They're excellent with children they're raised with but can be reserved with strangers. Their double coat sheds year-round and needs regular brushing. These dogs thrive when given a job to do and form incredibly strong bonds with their families. Originally bred in Germany for herding sheep, they've become one of the most versatile working breeds. They excel in police work, military service, search and rescue, and as service dogs. Their keen intelligence makes them quick learners, but they need firm, fair leadership. Regular health screenings are important as they're prone to hip dysplasia. These noble dogs combine courage with a gentle nature toward their loved ones.`,
  
  'Siberian Husky': `Siberian Huskies are energetic, friendly dogs bred for endurance in harsh climates by the Chukchi people of Siberia. These social, pack-oriented dogs are known for their striking appearance, piercing blue or brown eyes, and vocal nature. They need substantial daily exercise and do best with active families who can provide mental stimulation. Huskies are intelligent but independent, making training a patient endeavor that requires consistency. They're typically good with children and other dogs but have high prey drive toward small animals. Their thick double coat requires regular brushing and sheds heavily twice yearly. These accomplished escape artists need secure fencing and plenty of mental stimulation to prevent destructive behavior. Their incredible endurance made them famous during the 1925 serum run to Nome, Alaska. These working dogs thrive in cold weather but can adapt to warmer climates with proper care and air conditioning.`,
  
  'Staffordshire Bull Terrier': `Staffordshire Bull Terriers, or "Staffies," are muscular, affectionate dogs known for their love of people and legendary devotion to family. Despite their tough appearance, they're gentle souls, especially with children, earning the nickname "nanny dogs." Originally bred in 19th century England, these energetic companions need regular exercise and mental stimulation to stay balanced. They're intelligent and eager to please but can be strong-willed, requiring consistent, positive training. Staffies typically love other dogs when properly socialized from an early age. Their short, smooth coat is low-maintenance, requiring only occasional brushing. These loyal dogs form incredibly strong bonds with their families and thrive on human companionship, making them excellent family pets for active households. Their courage and determination make them natural protectors, while their playful nature ensures they're always ready for fun. They do best with owners who understand their need for both physical activity and emotional connection.`,
  
  'French Bulldog': `French Bulldogs are charming, affectionate companions perfect for apartment living. These adaptable dogs are known for their distinctive "bat ears," wrinkled faces, and playful personalities. They're excellent with children and make wonderful family pets due to their patient, gentle nature. Frenchies need minimal exercise but enjoy short walks and playtime, making them ideal for less active owners. Their flat faces mean they're sensitive to heat and need climate-controlled environments to prevent breathing difficulties. They can be stubborn but respond well to positive training and food motivation. These social butterflies love being center of attention and thrive on human interaction. Their minimal grooming needs and calm indoor demeanor make them ideal urban companions. These adaptable dogs are equally happy in small apartments or large homes, as long as they're with their beloved families.`,
  
  'Beagle': `Beagles are friendly, curious hounds with merry personalities and excellent noses developed for rabbit hunting in England. These pack dogs are social and typically great with children and other dogs, making them ideal family companions. They're sturdy, medium-sized dogs who need regular exercise to prevent weight gain, as they're prone to obesity. Beagles can be vocal and will "bay" when excited or following a scent trail, which potential owners should consider. Their strong hunting instincts mean they need secure fencing and leash walking, as they'll follow interesting scents anywhere. They're intelligent but can be stubborn, often following their noses over commands during training sessions. Their short, weather-resistant coat is easy to maintain with regular brushing. These cheerful, even-tempered dogs make wonderful family pets for active households who can provide mental stimulation. Their gentle nature and moderate size have made them one of America's most popular family dogs for generations.`,
  
  'Cavalier King Charles Spaniel': `Cavalier King Charles Spaniels are gentle, affectionate toy spaniels perfect for companionship. These adaptable dogs are equally happy on adventures or cuddling on laps, embodying the perfect balance of sporting dog and lap dog. They're excellent with children, seniors, and other pets, making them ideal for multi-generational households. Cavaliers are intelligent and eager to please, making training enjoyable. They need moderate exercise and love interactive play, but are content with daily walks and indoor games. Their silky coat comes in four color combinations and requires regular brushing to prevent tangles. These social dogs don't do well alone for long periods and thrive on human companionship. Their sweet, gentle nature and portable size make them ideal therapy dogs and family companions. They're prone to certain health issues, so choosing reputable rescue organizations is essential.`,
  
  'Labrador Retriever': `Labrador Retrievers are friendly, outgoing dogs known for their love of everyone they meet and unwavering loyalty. Originally bred in Newfoundland to help fishermen, these energetic companions excel as family pets, therapy dogs, and working partners. Labs are highly intelligent and eager to please, making them very trainable for both basic obedience and complex tasks. They need substantial daily exercise and love swimming, thanks to their water-resistant coat and webbed feet. These food-motivated dogs can gain weight easily, requiring careful portion control and regular activity. Labs are excellent with children and typically good with other pets, making them ideal family dogs. Their short, dense double coat sheds year-round and comes in yellow, black, or chocolate colors. These loyal, patient dogs thrive in active families who can match their enthusiasm for life. Their versatility has made them one of America's most popular breeds.`,
  
  'Jack Russell Terrier': `Jack Russell Terriers are small dogs with enormous personalities and endless energy. These intelligent, fearless terriers were bred for fox hunting and retain incredibly strong prey drive and determination. They need extensive daily exercise and mental stimulation to prevent destructive behavior, as boredom leads to creative mischief. JRTs are clever and independent thinkers, requiring patient, consistent training from owners who can match their wit. They can be territorial with other dogs and may not suit homes with small pets like cats or rabbits. Their minimal grooming needs are offset by their exceptionally high activity requirements. These spirited, athletic dogs are best for experienced, active owners who appreciate their bold, entertaining nature and can provide adequate physical and mental challenges. Despite their small size, they're fearless and will take on much larger opponents, requiring careful supervision and secure fencing.`,
  
  'Border Collie': `Border Collies are brilliant herding dogs considered the most intelligent breed, originally developed in the Scottish Borders for sheep herding. These intense, focused workers need jobs to stay happy and balanced, as their incredible intelligence requires constant mental challenges. They require extensive physical and mental exercise daily, often needing several hours of activity and stimulation. Border Collies excel at dog sports, obedience training, and agility but can develop obsessive behaviors without proper outlets. They're loyal and affectionate with family but may be reserved with strangers, sometimes showing herding instincts with children and other pets. Their weather-resistant double coat needs regular brushing and comes in various colors, most commonly black and white. These dogs aren't suited for casual pet owners; they thrive with active, dedicated handlers who understand their working nature and can channel their incredible drive into productive activities.`,
  
  'Bulldog': `Bulldogs are gentle, affectionate companions known for their distinctive wrinkled faces, pushed-in noses, and sturdy, muscular builds. Despite their tough appearance, they're sweet-natured and excellent with children, earning them the title of ideal family pets. Originally bred in England for bull-baiting, modern Bulldogs are peaceful, low-energy dogs perfect for apartment living, needing only moderate exercise due to their breathing limitations. Bulldogs are prone to overheating and need climate-controlled environments, especially during summer months. They can be stubborn but respond well to patient, consistent training with positive reinforcement. Their facial wrinkles need regular cleaning to prevent skin infections. These loyal, comical dogs form incredibly strong bonds with their families and are known for their entertaining personalities. Their calm demeanor and minimal exercise needs make them ideal companions for less active households.`,
  
  'Poodle': `Poodles are intelligent, athletic dogs that come in three sizes (Standard, Miniature, and Toy) but share similar temperaments and remarkable intelligence. Originally bred in Germany as water retrievers, these highly trainable companions excel at various activities from agility and obedience to therapy work and competitive sports. They're typically good with children and other pets when properly socialized. Poodles need regular exercise and mental stimulation to prevent boredom, as their active minds require constant engagement. Their curly, hypoallergenic coat requires professional grooming every 6-8 weeks and daily brushing to prevent matting. They're sensitive, intuitive dogs who thrive on positive reinforcement and form deep bonds with their families. These elegant, playful dogs make excellent family pets for those willing to maintain their grooming needs and match their active nature. Their versatility and trainability have made them popular choices for service work.`,
  
  'Yorkshire Terrier': `Yorkshire Terriers are tiny dogs with big personalities and brave hearts, originally bred in 19th century England to catch rats in textile mills. These portable companions are deeply affectionate with family members but can be suspicious of strangers, making them excellent watchdogs despite their small size. Yorkies are intelligent and trainable but can be stubborn, requiring patient training. Despite their toy size, they need daily exercise and mental stimulation. Their long, silky coat requires daily brushing to prevent matting and regular professional grooming. They can be quite vocal and make excellent alert dogs, though this trait may need management in apartment settings. These terriers may not suit homes with very young children due to their delicate size and sometimes snappy nature when mishandled. Their adaptability, loyalty, and small size make them perfect for apartment living with devoted owners who understand their terrier temperament.`,
  
  'Shih Tzu': `Shih Tzus are affectionate lap dogs bred for companionship in Chinese imperial palaces, where they were treasured by royalty for centuries. These friendly, outgoing dogs love everyone they meet and make excellent family pets with their naturally happy disposition. They're remarkably adaptable to various living situations and need only moderate exercise, making them perfect for apartment life. Shih Tzus are intelligent but can be stubborn during training, responding best to positive reinforcement and patience. Their long, luxurious double coat comes in many color combinations and requires daily brushing and regular professional grooming. They're typically excellent with children and other pets when properly socialized. These brachycephalic dogs don't tolerate heat well due to their flat faces and may need climate control in warm weather. Their cheerful disposition, portable size, and loving nature make them ideal companions for apartments, seniors, and families seeking a devoted companion who thrives on human attention.`,
  
  'Lurcher': `Lurchers are unique sighthound crosses, typically combining Greyhounds or Whippets with terriers or collies, creating dogs that blend speed with intelligence. Originally developed by poachers in Britain, these gentle, affectionate dogs make wonderful family companions despite their hunting heritage. They need regular exercise but are remarkably calm indoors, earning them the nickname "part-time athletes" for switching between intense activity and complete relaxation. Lurchers are typically excellent with children and can live harmoniously with other dogs when properly introduced. Their thin skin and lean build mean they need warm bedding and coats in winter weather. They retain strong prey drive toward small animals and need secure areas for off-leash exercise. These adaptable dogs come in various sizes and coat types depending on their parentage, but all share the sighthound's gentle nature. They suit various households that understand their sighthound nature and appreciate their unique combination.`,
  
  'Mixed Breed': `Mixed breed dogs combine traits from multiple breeds, creating unique personalities and appearances that make each dog truly one-of-a-kind. These special companions often have fewer inherited health issues due to genetic diversity, a phenomenon known as hybrid vigor. Every mixed breed is different, with temperaments ranging from calm to energetic, sizes from tiny to large, making them suitable for various lifestyles. They can excel at any activity from couch warming to agility, therapy work to hiking adventures. Mixed breeds often display the best qualities of their component breeds while mellowing extreme traits. Their unpredictable adult size and temperament make them delightful adventures, keeping families guessing about their dog's final appearance and personality. These special dogs prove that pedigree isn't necessary for unconditional love, loyalty, and the perfect family match. Rescue mixed breeds particularly shine as grateful, devoted companions who seem to understand they've been given a second chance.`
};

/**
 * Get breed description for a specific breed
 * @param {string} breedName - Name of the breed
 * @returns {string|null} - Breed description or null if not found
 */
export function getBreedDescription(breedName) {
  if (!breedName) return null;
  
  // Normalize breed name (trim and handle case)
  const normalizedBreed = breedName.trim();
  
  // Try exact match first
  if (BREED_DESCRIPTIONS[normalizedBreed]) {
    return BREED_DESCRIPTIONS[normalizedBreed];
  }
  
  // Try case-insensitive match
  const breedKey = Object.keys(BREED_DESCRIPTIONS).find(
    key => key.toLowerCase() === normalizedBreed.toLowerCase()
  );
  
  return breedKey ? BREED_DESCRIPTIONS[breedKey] : null;
}

/**
 * Get all available breed descriptions
 * @returns {Object} - Object with all breed descriptions
 */
export function getAllBreedDescriptions() {
  return { ...BREED_DESCRIPTIONS };
}

/**
 * Check if a breed has a description available
 * @param {string} breedName - Name of the breed
 * @returns {boolean} - True if description exists
 */
export function hasBreedDescription(breedName) {
  return getBreedDescription(breedName) !== null;
}

export default {
  getBreedDescription,
  getAllBreedDescriptions,
  hasBreedDescription
};